FROM node:20-bookworm-slim

WORKDIR /workspace

COPY package*.json ./
RUN npm ci

COPY index.html vite.config.js eslint.config.js ./
COPY public ./public
COPY votely-mobile ./votely-mobile

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
